Feature / create & style header
liemgumball/html-css-training pull request #18
Opened 2023-06-26 09:09 UTC by liemgumball

- Added head logo
![image](https://github.com/liemgumball/html-css-training/assets/92854999/a31f6f84-f19d-4ee5-8258-dd213f7a2d4c)

- Created and styled header in Mobile-first
![image](https://github.com/liemgumball/html-css-training/assets/92854999/92e5f129-bdc0-42c6-bda8-c956079bd2fe)

- Applied hover animation to drop menu (which have authencation buttons)
![image](https://github.com/liemgumball/html-css-training/assets/92854999/6c5b6cae-c123-4963-a1a6-aa4717f008be)

- Styled for Tablet (the menu doesn't have authencation buttons)
![image](https://github.com/liemgumball/html-css-training/assets/92854999/41f004a9-61a8-470e-99e2-93b28a1f6cfa)

- Styled for Desktop
![image](https://github.com/liemgumball/html-css-training/assets/92854999/e74df2ce-c101-4948-b5fc-4ff9c4e345d3)

2023-06-26 09:17 UTC, huyenpham-agilityio commented
the menu on mobile is not good. Please refer other website

2023-06-26 10:21 UTC, liemgumball commented
- Updated style the menu on mobile (tablet also)
![image](https://github.com/liemgumball/html-css-training/assets/92854999/d08c93a0-064c-4dba-9b46-ae1af1aad4f4)
![image](https://github.com/liemgumball/html-css-training/assets/92854999/7684e3ae-71a4-4172-84a4-fa194ef56625)

2023-06-26 10:53 UTC, liemgumball commented
- Updated style the menu on mobile (tablet also)
![image](https://github.com/liemgumball/html-css-training/assets/92854999/2cb07620-2b2e-48eb-99c7-da3f8b2fdb6d)
![image](https://github.com/liemgumball/html-css-training/assets/92854999/c72e61b8-e994-4d5f-984c-f16a610e08f3)

2023-06-27 02:19 UTC, huyenpham-agilityio requested changes

2023-06-27 02:19 UTC, huyenpham-agilityio commented on practice-2/src/assets/css/layout/header.css
> +    border: none !important;
avoid use important please, double check for other cases

2023-06-27 02:19 UTC, huyenpham-agilityio commented on practice-2/src/assets/css/layout/header.css
> +    border: 1px solid #eeeeee;
do you have variable for this color?

2023-06-27 02:19 UTC, huyenpham-agilityio commented on practice-2/src/assets/css/layout/header.css
> +        border: 1px solid #eeeeee;
ditto

2023-06-27 02:19 UTC, huyenpham-agilityio commented on practice-2/src/assets/css/layout/header.css
> +        box-shadow: 0 1px 3px rgba(31, 35, 40, 0.12),
this is duplicated somewhere, can you create variable?

2023-06-27 02:44 UTC, huyenpham-agilityio approved these changes

2023-06-27 02:44 UTC, merged